export const ExampleInput = {
  shifts: [
    {
      shiftName: "Bimi früh",
      necesarry: true,
      weekend: false,
      position: "Bimi",
    },
    {
      shiftName: "Bimi spät",
      necesarry: true,
      weekend: false,
      position: "Bimi",
    },
    {
      shiftName: "Bimi Wochenende",
      necesarry: true,
      weekend: true,
      position: "Bimi",
    },
  ],
  employees: [
    { name: "Alpay Yeşildağlar", workDays: "20", positionsArr: ["Bimi"] },
    {
      name: "Christian Daubitz",
      workDays: "20",
      positionsArr: ["Bimi", "Technik"],
    },
    {
      name: "Fred Gneckow",
      workDays: "20",
      positionsArr: ["AudioMischer", "VR", "AudioRunner", "Skype", "GFX"],
    },
    {
      name: "Oliver Löytved- Hardegg",
      workDays: "20",
      positionsArr: ["VR", "DP"],
    },
    { name: "Philipp Hill", workDays: "20", positionsArr: ["Holo", "Bimi"] },
    { name: "Sascha Wöpke", workDays: "20", positionsArr: ["Technik"] },
    { name: "Andy Eichhorst", workDays: "12", positionsArr: ["Bimi"] },
    {
      name: "Christian Friedrich",
      workDays: "12",
      positionsArr: ["Bimi", "AudioMischer", "AudioRunner", "Skype", "GFX"],
    },
    {
      name: "Christian Würfel",
      workDays: "12",
      positionsArr: ["Skype", "GFX", "VR"],
    },
    {
      name: "Claudio Bader",
      workDays: "12",
      positionsArr: ["Skype", "GFX", "VR"],
    },
    {
      name: "Daniel Matz",
      workDays: "12",
      positionsArr: ["AudioRunner", "AudioMischer", "VR", "GFX", "Skype"],
    },
    {
      name: "Danny Weber",
      workDays: "12",
      positionsArr: ["AudioRunner", "AudioMischer", "VR"],
    },
    {
      name: "Enrico Wolf",
      workDays: "12",
      positionsArr: ["Skype", "GFX", "VR"],
    },
    { name: "Flo Mathy", workDays: "12", positionsArr: ["Skype", "GFX", "VR"] },
    {
      name: "Freddy Hausburg",
      workDays: "4",
      positionsArr: ["GFX", "Skype", "AudioRunner", "VR"],
    },
    {
      name: "Ivo Grosche",
      workDays: "12",
      positionsArr: ["Skype", "GFX", "VR"],
    },
    {
      name: "Jean Djaman",
      workDays: "12",
      positionsArr: ["Skype", "GFX", "VR"],
    },
    {
      name: "Leopold Dreyer",
      workDays: "12",
      positionsArr: ["AudioRunner", "AudioMischer"],
    },
    {
      name: "Luis Meißner",
      workDays: "12",
      positionsArr: ["AudioRunner", "AudioMischer"],
    },
    {
      name: "Mark Papworth",
      workDays: "12",
      positionsArr: ["Skype", "GFX", "VR"],
    },
    {
      name: "Martin Glogowski",
      workDays: "12",
      positionsArr: ["Skype", "GFX", "VR"],
    },
    { name: "Matthias Gubisch", workDays: "12", positionsArr: ["Bimi"] },
    {
      name: "Mike Einhorn",
      workDays: "12",
      positionsArr: ["Skype", "GFX", "VR"],
    },
    {
      name: "Moritz Zuchantke",
      workDays: "12",
      positionsArr: ["Skype", "GFX", "VR"],
    },
    {
      name: "Philipp Drube",
      workDays: "12",
      positionsArr: ["Skype", "GFX", "VR"],
    },
    {
      name: "Ray Kajioka",
      workDays: "12",
      positionsArr: ["Skype", "GFX", "VR"],
    },
    {
      name: "Robin Gansler",
      workDays: "12",
      positionsArr: ["Skype", "GFX", "VR"],
    },
    {
      name: "Steven Daumann",
      workDays: "12",
      positionsArr: ["Skype", "GFX", "VR"],
    },
    {
      name: "Torsten Blaufuss",
      workDays: "12",
      positionsArr: ["Skype", "GFX", "VR"],
    },
    {
      name: "Uli Wiesner",
      workDays: "12",
      positionsArr: ["Skype", "GFX", "VR"],
    },
    { name: "Yves Kasten", workDays: "", positionsArr: [] },
  ],
  positions: [
    "Bimi",
    "Technik",
    "AudioMischer",
    "VR",
    "AudioRunner",
    "Skype",
    "GFX",
    "DP",
    "Holo",
  ],
  calendarMonth: [
    {
      day: 1,
      month: 5,
      year: 2021,
      weekdayString: "Sat",
      isWeekendHolyday: true,
      date: "01.05.21",
    },
    {
      day: 2,
      month: 5,
      year: 2021,
      weekdayString: "Sun",
      isWeekendHolyday: true,
      date: "02.05.21",
    },
    {
      day: 3,
      month: 5,
      year: 2021,
      weekdayString: "Mon",
      isWeekendHolyday: false,
      date: "03.05.21",
    },
    {
      day: 4,
      month: 5,
      year: 2021,
      weekdayString: "Tue",
      isWeekendHolyday: false,
      date: "04.05.21",
    },
    {
      day: 5,
      month: 5,
      year: 2021,
      weekdayString: "Wed",
      isWeekendHolyday: false,
      date: "05.05.21",
    },
    {
      day: 6,
      month: 5,
      year: 2021,
      weekdayString: "Thur",
      isWeekendHolyday: false,
      date: "06.05.21",
    },
    {
      day: 7,
      month: 5,
      year: 2021,
      weekdayString: "Fri",
      isWeekendHolyday: false,
      date: "07.05.21",
    },
    {
      day: 8,
      month: 5,
      year: 2021,
      weekdayString: "Sat",
      isWeekendHolyday: true,
      date: "08.05.21",
    },
    {
      day: 9,
      month: 5,
      year: 2021,
      weekdayString: "Sun",
      isWeekendHolyday: true,
      date: "09.05.21",
    },
    {
      day: 10,
      month: 5,
      year: 2021,
      weekdayString: "Mon",
      isWeekendHolyday: false,
      date: "10.05.21",
    },
    {
      day: 11,
      month: 5,
      year: 2021,
      weekdayString: "Tue",
      isWeekendHolyday: false,
      date: "11.05.21",
    },
    {
      day: 12,
      month: 5,
      year: 2021,
      weekdayString: "Wed",
      isWeekendHolyday: false,
      date: "12.05.21",
    },
    {
      day: 13,
      month: 5,
      year: 2021,
      weekdayString: "Thur",
      isWeekendHolyday: false,
      date: "13.05.21",
    },
    {
      day: 14,
      month: 5,
      year: 2021,
      weekdayString: "Fri",
      isWeekendHolyday: false,
      date: "14.05.21",
    },
    {
      day: 15,
      month: 5,
      year: 2021,
      weekdayString: "Sat",
      isWeekendHolyday: true,
      date: "15.05.21",
    },
    {
      day: 16,
      month: 5,
      year: 2021,
      weekdayString: "Sun",
      isWeekendHolyday: true,
      date: "16.05.21",
    },
    {
      day: 17,
      month: 5,
      year: 2021,
      weekdayString: "Mon",
      isWeekendHolyday: false,
      date: "17.05.21",
    },
    {
      day: 18,
      month: 5,
      year: 2021,
      weekdayString: "Tue",
      isWeekendHolyday: false,
      date: "18.05.21",
    },
    {
      day: 19,
      month: 5,
      year: 2021,
      weekdayString: "Wed",
      isWeekendHolyday: false,
      date: "19.05.21",
    },
    {
      day: 20,
      month: 5,
      year: 2021,
      weekdayString: "Thur",
      isWeekendHolyday: false,
      date: "20.05.21",
    },
    {
      day: 21,
      month: 5,
      year: 2021,
      weekdayString: "Fri",
      isWeekendHolyday: false,
      date: "21.05.21",
    },
    {
      day: 22,
      month: 5,
      year: 2021,
      weekdayString: "Sat",
      isWeekendHolyday: true,
      date: "22.05.21",
    },
    {
      day: 23,
      month: 5,
      year: 2021,
      weekdayString: "Sun",
      isWeekendHolyday: true,
      date: "23.05.21",
    },
    {
      day: 24,
      month: 5,
      year: 2021,
      weekdayString: "Mon",
      isWeekendHolyday: false,
      date: "24.05.21",
    },
    {
      day: 25,
      month: 5,
      year: 2021,
      weekdayString: "Tue",
      isWeekendHolyday: false,
      date: "25.05.21",
    },
    {
      day: 26,
      month: 5,
      year: 2021,
      weekdayString: "Wed",
      isWeekendHolyday: false,
      date: "26.05.21",
    },
    {
      day: 27,
      month: 5,
      year: 2021,
      weekdayString: "Thur",
      isWeekendHolyday: false,
      date: "27.05.21",
    },
    {
      day: 28,
      month: 5,
      year: 2021,
      weekdayString: "Fri",
      isWeekendHolyday: false,
      date: "28.05.21",
    },
    {
      day: 29,
      month: 5,
      year: 2021,
      weekdayString: "Sat",
      isWeekendHolyday: true,
      date: "29.05.21",
    },
    {
      day: 30,
      month: 5,
      year: 2021,
      weekdayString: "Sun",
      isWeekendHolyday: true,
      date: "30.05.21",
    },
    {
      day: 31,
      month: 5,
      year: 2021,
      weekdayString: "Mon",
      isWeekendHolyday: false,
      date: "31.05.21",
    },
  ],
  availability: {
    
    "01.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "Kann Früh" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "" },
      { name: "Philipp Hill", availability: "Kann Früh" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "Urlaub" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "Kann Früh" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "Kann Früh" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "Urlaub" },
      { name: "Moritz Zuchantke", availability: "Kann Früh" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "Kann Früh" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "Urlaub" },
    ],
    "02.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "Kann nicht" },
      { name: "Fred Gneckow", availability: "Kann Früh" },
      { name: "Oliver Löytved-Hardegg", availability: "" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "Kann Früh" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "Kann nicht" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "Kann Früh" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "" },
      { name: "Mark Papworth", availability: "Kann Früh" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "Urlaub" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "Kann Früh" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "Kann Früh" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "03.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "Urlaub" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "Kann nicht" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "Kann nicht" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "Urlaub" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "Kann nicht" },
      { name: "Leopold Dreyer", availability: "Kann Früh" },
      { name: "Luis Meißner", availability: "" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "Kann Früh" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "Kann nicht" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "04.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "Urlaub" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "Kann" },
      { name: "Andy Eichhorst", availability: "Kann Früh" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "Kann Früh" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "Urlaub" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "Kann nicht" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "Kann nicht" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "Urlaub" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "Kann" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "Urlaub" },
    ],
    "05.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "Kann" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "Kann nicht" },
      { name: "Christian Würfel", availability: "Kann Früh" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "Kann Früh" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "Urlaub" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "Kann" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "Kann" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "06.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "Kann Früh" },
      { name: "Oliver Löytved-Hardegg", availability: "" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "Urlaub" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "Kann nicht" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "Kann nicht" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "Kann Früh" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "07.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "Kann nicht" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "Urlaub" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "Kann" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "Kann Früh" },
      { name: "Luis Meißner", availability: "" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "Kann Früh" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "Urlaub" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "Kann nicht" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "08.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "Urlaub" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "Kann" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "Kann nicht" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "Kann nicht" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "Urlaub" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "Kann" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "09.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "Kann Früh" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "Kann Früh" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "Urlaub" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "Kann nicht" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "10.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "Kann nicht" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "Kann nicht" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "Urlaub" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "Kann" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "11.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "12.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "Kann Früh" },
      { name: "Oliver Löytved-Hardegg", availability: "" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "Kann Früh" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "Urlaub" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "Kann Früh" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "Kann Früh" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "13.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "Kann nicht" },
      { name: "Philipp Hill", availability: "Kann Früh" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "Kann Früh" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "Kann nicht" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "14.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "Urlaub" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "Kann nicht" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "Kann nicht" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "Urlaub" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "Kann" },
      { name: "Luis Meißner", availability: "" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "Kann Früh" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "Kann Früh" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "Urlaub" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "15.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "Urlaub" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "Kann" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "Kann" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "Kann nicht" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "Kann nicht" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "16.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "Kann Früh" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "Urlaub" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "Kann" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "Kann" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "17.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "" },
      { name: "Philipp Hill", availability: "Kann Früh" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "Kann Früh" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "Urlaub" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "Kann nicht" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "Urlaub" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "18.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "Kann nicht" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "Kann nicht" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "Urlaub" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "Kann" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "Urlaub" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "19.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "Kann Früh" },
      { name: "Oliver Löytved-Hardegg", availability: "" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "Kann Früh" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "Urlaub" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "Kann Früh" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "Kann Früh" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "20.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "Kann nicht" },
      { name: "Philipp Hill", availability: "Kann Früh" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "Kann Früh" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "Kann nicht" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "21.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "Urlaub" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "Kann nicht" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "Kann nicht" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "Urlaub" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "Kann" },
      { name: "Luis Meißner", availability: "" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "22.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "Urlaub" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "Kann" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "Kann" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "23.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "Kann Früh" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "Kann Früh" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "Urlaub" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "Kann Früh" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "Kann Früh" },
      { name: "Luis Meißner", availability: "" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "24.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "Kann nicht" },
      { name: "Oliver Löytved-Hardegg", availability: "Kann Früh" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "Kann Früh" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "Kann nicht" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "25.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "Urlaub" },
      { name: "Oliver Löytved-Hardegg", availability: "" },
      { name: "Philipp Hill", availability: "Kann nicht" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "Kann nicht" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "Urlaub" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "Kann" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "Kann" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "26.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "" },
      { name: "Philipp Hill", availability: "Urlaub" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "Kann" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "Kann" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "Kann" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "27.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "Kann Früh" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "28.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "Kann Früh" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "Kann Früh" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "Urlaub" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "Kann nicht" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "29.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "" },
      { name: "Philipp Hill", availability: "Kann nicht" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "Kann nicht" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "Urlaub" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "Kann" },
      { name: "Luis Meißner", availability: "" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "30.04.21": [
      { name: "Alpay Yeşildağlar ", availability: "" },
      { name: "Christian Daubitz", availability: "" },
      { name: "Fred Gneckow", availability: "" },
      { name: "Oliver Löytved-Hardegg", availability: "" },
      { name: "Philipp Hill", availability: "" },
      { name: "Sascha Wöpke", availability: "" },
      { name: "Andy Eichhorst", availability: "" },
      { name: "Christian Friedrich", availability: "" },
      { name: "Christian Würfel", availability: "" },
      { name: "Claudio Bader", availability: "" },
      { name: "Daniel Matz", availability: "" },
      { name: "Danny Weber", availability: "" },
      { name: "Enrico Wolf", availability: "" },
      { name: "Flo Mathy", availability: "" },
      { name: "Freddy Hausburg", availability: "" },
      { name: "Ivo Grosche", availability: "" },
      { name: "Jean Djaman", availability: "" },
      { name: "Leopold Dreyer", availability: "" },
      { name: "Luis Meißner", availability: "" },
      { name: "Mark Papworth", availability: "" },
      { name: "Martin Glogowski", availability: "" },
      { name: "Matthias Gubisch", availability: "" },
      { name: "Mike Einhorn", availability: "" },
      { name: "Moritz Zuchantke", availability: "" },
      { name: "Philipp Drube", availability: "" },
      { name: "Ray Kajioka", availability: "" },
      { name: "Robin Gansler", availability: "" },
      { name: "Steven Daumann", availability: "" },
      { name: "Torsten Blaufuss", availability: "" },
      { name: "Uli Wiesner", availability: "" },
      { name: "Yves Kasten", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
      { name: "", availability: "" },
    ],
    "31.XX.21": [
      { name: "Alpay Yeşildağlar ", availability: "\r" },
      { name: "Christian Daubitz", availability: "\r" },
      { name: "Fred Gneckow", availability: "\r" },
      { name: "Oliver Löytved-Hardegg", availability: "\r" },
      { name: "Philipp Hill", availability: "\r" },
      { name: "Sascha Wöpke", availability: "\r" },
      { name: "Andy Eichhorst", availability: "\r" },
      { name: "Christian Friedrich", availability: "\r" },
      { name: "Christian Würfel", availability: "\r" },
      { name: "Claudio Bader", availability: "\r" },
      { name: "Daniel Matz", availability: "\r" },
      { name: "Danny Weber", availability: "\r" },
      { name: "Enrico Wolf", availability: "\r" },
      { name: "Flo Mathy", availability: "\r" },
      { name: "Freddy Hausburg", availability: "\r" },
      { name: "Ivo Grosche", availability: "\r" },
      { name: "Jean Djaman", availability: "\r" },
      { name: "Leopold Dreyer", availability: "\r" },
      { name: "Luis Meißner", availability: "\r" },
      { name: "Mark Papworth", availability: "\r" },
      { name: "Martin Glogowski", availability: "\r" },
      { name: "Matthias Gubisch", availability: "\r" },
      { name: "Mike Einhorn", availability: "\r" },
      { name: "Moritz Zuchantke", availability: "\r" },
      { name: "Philipp Drube", availability: "\r" },
      { name: "Ray Kajioka", availability: "\r" },
      { name: "Robin Gansler", availability: "\r" },
      { name: "Steven Daumann", availability: "\r" },
      { name: "Torsten Blaufuss", availability: "\r" },
      { name: "Uli Wiesner", availability: "\r" },
      { name: "Yves Kasten", availability: "\r" },
      { name: "", availability: "\r" },
      { name: "", availability: "\r" },
      { name: "", availability: "" },
    ],
  },
  bulkPositions: [],
  dataInputTab: "Month",
};
